# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14a1bafb59fe8643f649cf4108ff4e594ff3b66d04576f55c584687e06edb297ae45fd883300612808e451458aff49f1e10939c5d3c42dd70733f7999cf74373

test:
  secret_key_base: 20818469f4c2c764fe6de02d14113a594d7144b60ba029387f50fe86d0b3a9ec8d96cb09fe3618db61b0ab0244170fbd86414df3f0e96fd5a29a1e927e6c56ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
